[build]
  # Directory where your HTML files are (root directory)
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing.html]
  pretty_urls = true

[forms]
  # Specify maximum form submissions per month if needed
  # max_submissions = 100 