[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  
  # Default build command
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 